### ISSUE TITLE
Tracking: Make Solus happy again

### ISSUE THREAD

**Issue by ikeydoherty** [clearlinux/clr-boot-manager#84]
Tracking some issues here as I'll need to follow up with some PRs to restore git master functionality.

Currently tests will fail UNLESS `--with-bootloader=shim-systemd-boot`. In Travis this passes only because the `auto` mode will fallback to `shim-systemd-boot`. All other options will fail on `check_uefi`.

There is also the issue of files having moved into `kernel/` subdirectory, so I'll need to track migration paths.

AR ikey:

 - [x] Make `--with-bootloader=goofiboot` work again (and for all sd class.)
 - [x] Prep Travis PR to build in multiple configurations (shim and systemd-class)
 - [ ] Add migration path for `kernel/` tree moving

General:

 - [x] `distcheck` is broken on master (William found this) - cmdline tests no longer pass. LIkely related to the above issue.
 - [ ] Need to update documentation around new shim system
 - [x] Configure doesn't check for `gnu-efi-devel` and `efivar-devel` (Solus names but yknow the dudes I mean)

**Comment by ikeydoherty** [comment]
Related: https://github.com/clearlinux/clr-boot-manager/pull/87

**Comment by ikeydoherty** [comment]
Much of this now fixed by merging #87 in cba2f74c8c4704b24ff1f0921dae906cc416842f

**Comment by bryteise** [comment]
So there isn't any need to do the migration path now correct? Still need to update the shim system though X(.

**Comment by ikeydoherty** [comment]
Ah right yeah this issue itself can prolly be closed or edited. What we actually need is EFI var management unbound from shim ^^

**Comment by dorileo** [comment]
Well, I'm closing this issue. Please feel free to reopen it or create new issues for features we've not implemented yet.

Thanks...
